# The purpose of this image is to serve the frontend app content separately.
# By default the Backstage backend uses the app-backend plugin to serve the
# app from the backend itself, but it may be desirable to move the frontend
# content serving to a separate deployment, in which case this image can be
# used.

# This dockerfile requires the app to be built on the host first, as it
# simply copies in the build output into the image. If you want to also perform
# the build itself inside docker, use Dockerfile.build in this folder instead.

# USAGE:
#
# - Copy this file and the "docker" folder from this directory to your project
#   root
#
# - Add the following line to your .dockerignore to make sure that the built
#   frontend actually can be transferred into the docker image:
#
#       !packages/app/dist
#
# - In your project root, run:
#
#       yarn install
#       yarn tsc
#       yarn workspace app build --config <config1> --config <config2> ...
#       docker build -t backstage-frontend -f Dockerfile.hostbuild .
#FROM node:20-bullseye AS builder
#FROM node:22-bookworm

# Install sqlite3 dependencies. You can skip this if you don't use sqlite3 in the image,
# in which case you should also move better-sqlite3 to "devDependencies" in package.json.
# Additionally, we install dependencies for `techdocs.generator.runIn: local`.
# https://backstage.io/docs/features/techdocs/getting-started#disabling-docker-in-docker-situation-optional


FROM ubuntu:22.04

# 필수 패키지 설치 + NodeSource PPA 추가 + Node.js 설치
RUN apt-get update && \
    apt-get install -y curl ca-certificates gnupg python3 python3-pip python3-venv build-essential && \
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Corepack 활성화 및 Yarn 4.4.1 설치
RUN corepack enable && \
    corepack prepare yarn@4.4.1 --activate

# (선택) Yarn 환경 확인
RUN node -v && yarn -v && corepack --version

WORKDIR /app

COPY . .

RUN yarn install --immutable

RUN yarn build:frontend
