apiVersion: v1
kind: Service
metadata:
  name: backstage-backend
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 7007
      targetPort: 7007
  selector:
    app: backstage-backend
