apiVersion: v1
kind: Service
metadata:
  name: backstage-frontend
  namespace: default
  labels:
    app: backstage-frontend
spec:
  selector:
    app: backstage-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP