apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-frontend
  namespace: default
  labels:
    app: backstage-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage-frontend
  template:
    metadata:
      labels:
        app: backstage-frontend
    spec:
      containers:
        - name: backstage-frontend
          image: kcufl/backstage-frontend:v0.0.1
          ports:
            - containerPort: 3000
              protocol: TCP
          imagePullPolicy: Always
      restartPolicy: Always

 
